---
output:
  bookdown::pdf_document2:
    template: ../templates/brief_template.tex
  bookdown::word_document2: default
  bookdown::html_document2: default
documentclass: book
bibliography: references/refs.bib
---

# **Discussion** {#chap:discussion}
\minitoc <!-- this will include a mini table of contents-->

\chaptermark{Discussion}

In the current study, we aimed to investigate the perception of multipoint image statistics in the two areas of the visual cortex that constitute the start and the highest level of rat’s putative ventral stream: area V1 (primary visual cortex) and area LL (laterolateral area). The method employed was acute recordings from these two areas in anesthetized rats while presenting them with a set of textures with a predefined statistical structure. The statistics in question were one-point ($\gamma$, gamma) correlations, two-point correlations ($\beta$, beta), three-point correlations ($\theta$, theta), and four-point correlations ($\alpha$, alpha).

\vspace{5mm}

A set of initial analyses was performed to investigate the properties of single multiunits, as well as global trends. Sparseness analysis revealed that V1 is generally sparser than LL, meaning higher selectivity overall. However, both areas have similar sparseness across the statistics. The higher selectivity measured on average in V1 can be due to LL higher tolerance and focus on global characteristics of the image; this means that while V1 was more selective for specific textures containing a statistic, LL could have been able to extract the statistical information from a texture without being selective for a specific texture sample. A further quantitative analysis of tuning curves revealed (see the summary presented in *Figure* \@ref(fig:Summary)) that V1 sensitivity shows a trend towards the same rank-ordered sensitivity to 1- to 4-point correlations that was observed in @Caramellino2021-pe, as well as in human studies reviewed in Chapter 1: *gamma > beta > alpha > theta*. Area LL was shown to have high selectivity for gamma, similar to V1, and some degree of selectivity for alpha, but low selectivity for beta and theta. Preliminary analysis of multiunits’ receptive field and response delay in V1 and LL confirmed the expected results coming from literature [@Tafazoli2017-yn; @Piasini2021-kc] with larger receptive fields and longer delay in LL, compared to small and highly focused receptive fields and lower response delay in LL. These differences are considered to be two of the basic conditions to confirm that the two areas form a hierarchical processing stream.

\vspace{5mm}

The decoding analysis demonstrated that V1 exhibits sensitivity to 1- and 2-point correlations (gamma and beta statistics, respectively), and no sensitivity to 3- and 4-point correlations (theta and alpha statistics). This finding is well in line with the previous studies in rats and monkeys. For instance, @Yu2015-cp  showed that sensitivity to 3- and 4-point correlations arised only in monkey’s V2, but was not found in V1. @Tafazoli2017-yn demonstrated that in rat visual cortex there is a progressive increase in the amount of information related to higher level features going from V1 to LL in an analogous way to what is observed in monkeys. This is confirmed by our results: V1 is only able to discriminate the simplest correlations related to global luminance and oriented bar patterns. A similar result was also observed by @Matteucci2019-xt, who showed that the shape selectivity of neurons increased in LL compared to V1, while the sharpness of orientation tuning declined. However, even though we found in V1 some sensitivity to 2-nd order (beta) correlations, it was lower than expected. This result might be due to the nature of this type of statistic: since it is a correlation between pairs of pixels, textures containing this statistic, unlike the 1-, 3- or 4-point correlations, clearly have a pattern that is oriented in a horizontal, vertical or diagonal way (see *Figure* \@ref(fig:TexExamples) for an example). For example, @Yu2015-cp set texture orientation according to the orientation preference of the target neuron before running the main experimental protocol. This approach can be used as a future direction to increase the amount of selective neurons in LL. This reasoning could also be applied to 3-point correlations that contain triangular elements, exhibiting some degree of orientation.

\vspace{5mm}

The results regarding area LL, on the contrary, only partially confirm our hypothesis. We suggested that LL should exhibit increased sensitivity to higher-order image statistics. Our results, however, show high selectivity to 1-point correlations (gamma statistic), similarly to V1, and very low selectivity for 2- (beta), low selectivity for 4-point (alpha) correlations. No selectivity for 3-point correlations (theta) was observed. These results are not fully in line with previous literature that shows stronger sensitivity to higher-order image statistics in extrastriate areas, in spite of the fact that we still observed a considerable increase in decoding performance for 4-point (alpha) statistic. We would also expect that in LL sensitivity to 3-point correlations should be significantly lower than sensitivity to 4-points - therefore, even though it is still unexpected that there was no sensitivity to 3-point correlations at all, the lower number of selective units for these correlations compared to 4-point statistic conforms to our hypothesis. Overall low decoding performance in area LL for higher-order correlations might be due to a number of reasons. First of all, our contradictory results might be due to the low amount of recorded neurons in LL selective for the presented higher-order statistics. This would mean that the presented low performances are due to the scarcity of obtained data and not because of LL per se not being sensitive to higher order correlations. This issue can be improved with more data obtained from LL. 

\vspace{5mm}

A rather unexpected finding was high LL selectivity for 1-order correlations (gamma). However, a previous study by @Tafazoli2017-yn showed that, although the importance of low-level features decreased along the progression from V1 to LL, these features – in particular, luminance - were still carrying a high amount of information about a stimulus. Therefore, it seems reasonable that high selectivity for 1-order correlations indeed remains in LL despite it being higher up in the visual system hierarchy.

\vspace{5mm}

An interesting point of discussion is the shape of LL tuning curves in response to gamma statistic that also influences the decoding performance. As can be seen in *Figure* \@ref(fig:GammaTC), the peak of sensitivity is reached when the level of the statistic equals 0.8. This tuning curve shape could be explained by the lack of structure in the texture with maximum gamma intensity (intensity of 1), which is a texture containing only white checks. Such textures might be less salient for higher level areas, such as LL, to discriminate from the mid-gray background, since the only activity is this sudden change in luminance, but not in structure. This explanation stems from a previous study by @Piasini2021-kc, who showed that area LL of rat visual cortex exhibits higher temporal stability of representations. Therefore, this finding implies that for higher visual areas, such as LL, a significant change in internal structure between a texture and a background might be needed to elicit LL activity. Despite a change in luminance, the difference between a completely white texture and a grey background may not be salient enough for LL to elicit activity.

\vspace{5mm}

One crutial issue we haven’t tackled is data preprocessing. One of the potential techniques to improve the quality of recorded data is spike sorting. This method clusters spikes based on their shape and occurence in time, allowing to classify each spike as belonging to a particular neuron. More discriminable and clean data might result in better decoding performance. We are currently starting to perform spike sorting for the available sessions using both the klustakwik-2 [@Rossant2016-om] package and the kilosort-2 package [@pachitariu2016kilosort] to be able to compare the two techniques and decide which is best for our data, but this analysis is still in its early stages. Moreover, regarding data preprocessing, it is necessary to develop a method for sessions recorded in LL to determine which channels were in LL and which - in other lower level lateral regions, such as LI and LM. This would considerably improve data quality, but it requires a detailed methodical examination of all LL sessions’ receptive fields.

\vspace{5mm}

A future direction would also be to analyze the multiunits' response to sparse noise movies that were part of our protocol. This additional step might give us a better understanding of neuronal tuning.

\vspace{5mm}

Given that the populations of selective multiunits we obtained are unbalanced between statistics, which makes it difficult to draw reliable conclusions when comparing sensitivity to different correlations both inside one area and between areas. In the future we aim to record more sessions in order to build more balanced subpopulations of neural units to use in our decoding process. This would give us a more clear view of the real decoding capabilities for each statistic in an area, as it would allow a more consistent comparison between the neurometric curves we obtain. At the same time it is important to highlight the fact that the scarcity of selective units for certain statistics is in itself an important result that we would like to confirm after collecting more data.

\vspace{5mm}

To summarize, our work  has confirmed the findings of the previous studies regarding V1 sensitivity to lower-order correlations and gave preliminary insights into the sensitivity of  LL to both low- and high-order correlations. The number of selective units in each area produces a ranking close to the one observed in humans, as well as rat sensitivity obtained from behavioral studies, with the only exception being that, compared to behavioral studies in rats, we found higher sensitivity in LL for 4-point correlations compared to 2-point correlations. However, more research is needed to address the aforementioned limitations. Overall, current results offer an interesting insight into the processing of multipoint correlations in rats visual cortex and further confirm the presence of a hierarchical organization among the areas forming rat putative ventral stream. This demonstrates, among other things, that textures can be an optimal class of stimuli to probe various research questions regarding perception of statistical properties of images. 
